# Default values for restore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The name of the CassandraRestore
name: restore

backup:
  name: bck-test
  cassandraDatacenter:
    name: k8s-dc1


cassandraDatacenter:
  name: k8s-dc1

# An in-place restore will restore the backup to the source cluster. Note that this will
# trigger a rolling restart of the cluster.
inPlace: false